version: '3.7'

services:
  apps:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECT="redis://redis:6379"
    networks:
      - network
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    networks:
      - network



networks:
  network:
    driver: bridge