version: '3.7'

services:
  apps1:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECT="redis://redis:6379"
    networks:
      - network
    volumes:
      - data:/data
    depends_on:
      - redis
  apps2:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECT="redis://redis:6379"
    networks:
      - network
    volumes:
      - data:/data
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    networks:
      - network


volumes:
  data:
networks:
  network:
    driver: bridge